### ISSUE TITLE
Question re ACF Pro after running setup?

### ISSUE THREAD

**Issue by bongoman** [fabrica-wp/fabrica-dev-kit#25]
Hi there

I ran setup.yml without my ACF credentials — how best to add my key after setup and init ?

**Comment by bongoman** [comment]
I actually edited setup.yml then ran `idk setup --reinstall`

and the command failed to complete:

`Activating 'advanced-custom-fields'...
Warning: Plugin 'advanced-custom-fields' is already active.
Success: Plugin already installed.
/usr/local/lib/node_modules/fabrica-dev-kit/index.js:244
				`&& rm /tmp/acf-pro.zip'`].join(' ')).code;
				^

TypeError: "&& wp plugin install /tmp/acf-pro.zip --activate" is not a function
    at Socket.install.stdout.on.on.on (/usr/local/lib/node_modules/fabrica-dev-kit/index.js:244:5)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by fewerflatlands** [comment]
This option only exists as a timesaver to auto-install ACF Pro for you at setup, so you don't have to do it manually. But if you neglect to put in the key, no need to reinstall FDK. Just install ACF Pro and put in your license key in the normal way in Plugins > Add New.
